- name: Play level variables
  hosts: localhost
  connection: local
  vars:
    url: play.example.com
  tasks:
    - name: Print url
      ansible.builtin.debug:
        msg: url - {{ url }}

- name: Task level variable
  hosts: localhost
  connection: local
  tasks:
    - name: Print url
      ansible.builtin.debug:
        msg: url - {{ url }}
      vars:
        url: task.examle.com